KZGlobalTeam/cs2kz-metamod

.github/workflows/build.yaml
Dockerfile
docker-entrypoint.sh

I've added a Dockerfile for building linux binaries against steamrt/sniper/sdk. I have also added automatic releases for windows and linux.
Build image
```sh
docker build . --file Dockerfile --tag cs2kz-linux-builder
```
Run image
```sh
docker run -v ./build:/app/build cs2kz-linux-builder
```

ADD: Dockerfile and release workflow

---

README.md

Adding Docker Instructions to README

Updating README.md with Docker Instructions

---

translations/cs2kz-checkpoint.phrases.txt
translations/cs2kz-commands.phrases.txt
translations/cs2kz-hud.phrases.txt
translations/cs2kz-jumpstats.phrases.txt
translations/cs2kz-modes.phrases.txt
translations/cs2kz-noclip.phrases.txt
translations/cs2kz-quiet.phrases.txt
translations/cs2kz-styles.phrases.txt
translations/cs2kz-timer.phrases.txt
translations/cs2kz-tips-general.phrases.txt
translations/cs2kz-tips-jumpstats.phrases.txt
translations/cs2kz-tips-visual.phrases.txt
translations/cs2kz-tips.phrases.txt

POLSKA GUROM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
skaye#5311
SneakY#6476
Szwagi#6028

Polish translation of cs2kz

---

translations/cs2kz-checkpoint.phrases.txt
translations/cs2kz-commands.phrases.txt
translations/cs2kz-hud.phrases.txt
translations/cs2kz-jumpstats.phrases.txt
translations/cs2kz-modes.phrases.txt
translations/cs2kz-noclip.phrases.txt
translations/cs2kz-quiet.phrases.txt
translations/cs2kz-styles.phrases.txt
translations/cs2kz-timer.phrases.txt
translations/cs2kz-tips-general.phrases.txt
translations/cs2kz-tips-jumpstats.phrases.txt
translations/cs2kz-tips-visual.phrases.txt
translations/cs2kz-tips.phrases.txt

Swedish translations

---

cfg/cs2kz.cfg

- remove `sv_holiday_mode` as it's obsolete.
- properly hide money from scoreboard as well.
- stop giving terrorists a c4 on spawn.
- make sure bots don't get killed on disconnect either.
- make rounds not have time
script created newline at the end of file, but it's gone now ? wack

Update some cvars

---

translations/cs2kz-commands.phrases.txt
translations/cs2kz-hud.phrases.txt
translations/cs2kz-styles.phrases.txt
translations/cs2kz-timer.phrases.txt

Someone smart can check them probs, should be fine for base

Add Finnish translations to missing phrases

---

.github/workflows/build-push-and-pr.yaml
.github/workflows/prevent-master-prs.yaml

fix repo path for protecting master, add common paths that don't affect build outcome to be ignored

Additions to workflows

---

translations/cs2kz-commands.phrases.txt
translations/cs2kz-goto.phrases.txt

Not so sure about the 1st phrase as it sounds silly in my mind, but alternatives sounded even sillier. Someone smarter and possibly not drunk can maybe come up with better ones again.

Finnish translations to Goto phrases

---

.github/workflows/build-dev-release.yaml
.github/workflows/build-push-and-pr.yaml
.github/workflows/build-release.yaml
.github/workflows/build.yaml
.github/workflows/prevent-master-prs.yaml

if some of these had a specific version for a reason, comment or just change

update workflows to get rid of deprecation warnings

---

translations/cs2kz-checkpoint.phrases.txt
translations/cs2kz-commands.phrases.txt
translations/cs2kz-goto.phrases.txt
translations/cs2kz-hud.phrases.txt
translations/cs2kz-jumpstats.phrases.txt
translations/cs2kz-modes.phrases.txt
translations/cs2kz-noclip.phrases.txt
translations/cs2kz-quiet.phrases.txt
translations/cs2kz-styles.phrases.txt
translations/cs2kz-timer.phrases.txt
translations/cs2kz-tips-general.phrases.txt
translations/cs2kz-tips-jumpstats.phrases.txt
translations/cs2kz-tips-visual.phrases.txt
translations/cs2kz-tips.phrases.txt

[IT] Italian translation of ./translations folder
+small indentation fix for [TR] translation

Italian translation

---

translations/cs2kz-commands.phrases.txt
translations/cs2kz-timer-coursetop.phrases.txt

Hi again I don't know if i translated the 'Course Top Command Usage' part right I will check either ingame or when other translations are done

turkish translations coursetop phrases & commands phrases

---

translations/cs2kz-commands.phrases.txt
translations/cs2kz-timer-coursetop.phrases.txt

Update of 16 Sept 2024: added 9 strings in cs2kz-commands.phrases.txt and new file cs2kz-timer-coursetop.phrases.txt

[IT] Italian translations update

---

translations/cs2kz-checkpoint.phrases.txt
translations/cs2kz-commands.phrases.txt
translations/cs2kz-goto.phrases.txt
translations/cs2kz-hud.phrases.txt
translations/cs2kz-jumpstats.phrases.txt
translations/cs2kz-modes.phrases.txt
translations/cs2kz-noclip.phrases.txt
translations/cs2kz-quiet.phrases.txt
translations/cs2kz-styles.phrases.txt
translations/cs2kz-timer-coursetop.phrases.txt
translations/cs2kz-timer-getrecords.phrases.txt
translations/cs2kz-timer-personalbest.phrases.txt
translations/cs2kz-timer.phrases.txt
translations/cs2kz-tips-general.phrases.txt
translations/cs2kz-tips-jumpstats.phrases.txt
translations/cs2kz-tips-visual.phrases.txt
translations/cs2kz-tips.phrases.txt

https://github.com/user-attachments/assets/4d601929-01f0-4e37-809b-5bc2fdba3055

german translation + few missing polish strings

---

translations/cs2kz-commands.phrases.txt
translations/cs2kz-course.phrases.txt

sv translations 

---

translations/cs2kz-commands.phrases.txt
translations/cs2kz-jumpstats.phrases.txt
translations/cs2kz-timer.phrases.txt

more swedish tr

---

translations/cs2kz-checkpoint.phrases.txt
translations/cs2kz-commands.phrases.txt
translations/cs2kz-common.phrases.txt
translations/cs2kz-course.phrases.txt
translations/cs2kz-goto.phrases.txt
translations/cs2kz-hud.phrases.txt
translations/cs2kz-jumpstats.phrases.txt
translations/cs2kz-modes.phrases.txt
translations/cs2kz-noclip.phrases.txt
translations/cs2kz-quiet.phrases.txt
translations/cs2kz-styles.phrases.txt
translations/cs2kz-timer-coursetop.phrases.txt
translations/cs2kz-timer-getrecords.phrases.txt
translations/cs2kz-timer-personalbest.phrases.txt
translations/cs2kz-timer.phrases.txt
translations/cs2kz-tips-general.phrases.txt
translations/cs2kz-tips-jumpstats.phrases.txt
translations/cs2kz-tips-timer.phrases.txt
translations/cs2kz-tips-visual.phrases.txt
translations/cs2kz-tips.phrases.txt

Add Korean Translation by discord .garam

Add ko translation

---

src/kz/global/kz_global.h

This was removed accidentally in #291

Add back missing function body

---

AMBuildScript

Related: https://github.com/JuliaLang/julia/issues/57250

Explicitly disable executable stack to be able to run on glibc 2.41+

---

src/kz/timer/kz_timer.cpp

Play some timer sounds to spectators

---

src/kz/mode/kz_mode_ckz.cpp
src/movement/mv_hooks.cpp
src/sdk/services.h

Forced subtick moves were not properly networked to players. This fixes that and add some more moves in the future.

Improve CKZ prediction

---

README.md

Took me a second to get this right on Windows, so figured I could help the next person.

Expand git clone instructions

---

src/kz/misc/kz_misc.cpp
src/player/player.h

Fix chat weirdness with quotes, speculative fix for names being randomly converted into lowercase

---

translations/cs2kz-commands.phrases.txt

Update cs2kz-commands.phrases.txt swedish

---

translations/cs2kz-commands.phrases.txt

translation add Simplified Chinese

Update translation chi cs2kz-commands.phrases.txt

---

translations/cs2kz-commands.phrases.txt

Removed duplicate line added along with Chinese translation

Fix duplicate line in cs2kz-commands.phrases.txt

---

translations/cs2kz-anticheat.phrases.txt
translations/cs2kz-api.phrases.txt
translations/cs2kz-common.phrases.txt
translations/cs2kz-course.phrases.txt
translations/cs2kz-timer-coursetop.phrases.txt

Added Finnish translations to a portion of existing documents.

Finnish translations

---

translations/cs2kz-language.phrases.txt

add chi cs2kz-language.phrases.txt

---

translations/cs2kz-commands.phrases.txt
translations/cs2kz-spec.phrases.txt

sv translations

---

translations/cs2kz-spec.phrases.txt

kz_spec ko update
